### ISSUE TITLE
 Call to undefined method zaporylie\Vipps\Vipps::payments()

### ISSUE THREAD

**Issue by andreassolemkjaer** [zaporylie/php-vipps#18]
This might be related to the currently open issue on errors in the docs, but when I run 

// Get payment API - pass product's subcription key obtainted from Developer Portal.
$payment = $app->payments('xxxxxxxx');

I get

Call to undefined method zaporylie\Vipps\Vipps::payments()

Also, it's not entire clear to me when I need to supply the Client Secret. Is the client secret the same as the product's subscription key?

When I try to do $app->payment($orderId); I get
Missing argument 2 for zaporylie\Vipps\Vipps::payment()

Do I need to supply the Client Secret to the payment method as well?

Thanks,
Andreas

**Comment by zaporylie** [comment]
Hi Andreas,

thank you for raising my awareness about documentation errors I've made. 

It is clearly to me that method you want use is this one - https://github.com/zaporylie/php-vipps/blob/1.x/src/Vipps.php#L50 - note that method name is `payment`, not `payments` (singular over plural). Documentation is outdated and refers to previous version of Vipps lib.

`\zaporylie\Vipps\Vipps::payment()` takes two parameters: `$subscription_key` and `$merchant_serial_number`. Both required and either one can be obtained from Vipps Developer Portal.

Sorry for inconvenience
Jakub

**Comment by andreassolemkjaer** [comment]
Ok, thanks! That helped, but now I'm getting an InvalidArgumentException saying "missing token". I believe I'm supplying all the necessary parameters:

`$client = new \zaporylie\Vipps\Client($settings['clientId']);`
`$app = new \zaporylie\Vipps\Vipps($client);`
`$payments = $app->payment($settings['inAppPrimaryKey'], $settings['merchantSerialNumber']);`
`$payments->initiatePayment($orderId, $mobileNumber, $amount, $description, $callbackUrl);`

Am I missing something in the authentication procedure? I can't see that I have to supply the client secret anywhere. Is this not used in this API? Is that why I have to use the subscription/primary key?

I'm currently just testing the API. Do I need to use some special merchant serial number while testing perhaps, or should I use the production serial number found in the vipps developer portal?

**Comment by ivareri** [comment]
I found i had to do a authentication step in addition to what is in the documentation
`
$auth = $app->authorization('access_subscription_key');
` 
`
$auth->getToken('client_secret');
`

I got two subscription keys from Vipps. I used the access subscription key in the authorization step over, and the eCommerce subscription key in the payment step

**Comment by zaporylie** [comment]
Perfect.

Please note that in `\zaporylie\Vipps\Client()` is responsible for Token storage. By default Token is stored in-memory using `\zaporylie\Vipps\Authentication\TokenMemoryCacheStorage()` - see https://github.com/zaporylie/php-vipps/blob/1.x/src/Authentication/TokenMemoryCacheStorage.php
You can create own class implementing TokenStorageInterface in order to store it somewhere else - in database or readis and re-use token cross-request.

**Comment by andreassolemkjaer** [comment]
Thanks!
I think I'm a little bit confused with what things are called in the Vipps Developers Portal. Right, so I have two subscriptions in the Vipps Developer Portal, one defined as product "Access Token" and the other defined as "InApp".
If I try to run the following with the primary key from the Access Token product and the primary key from the inApp product, it complains that my subscription key is invalid:
`$client = new \zaporylie\Vipps\Client($settings['clientId']);`
`$app = new \zaporylie\Vipps\Vipps($client);`
`$auth = $app->authorization($settings['accessTokenPrimaryKey']);`
`$token = $auth->getToken($settings['clientSecret']);`
`$payments = $app->payment($settings['inAppPrimaryKey'], $settings['merchantSerialNumber']);`
`$payments->initiatePayment($orderId, $mobileNumber, $amount, $description, $callbackUrl);`

Did I misunderstand something?

Again thanks for all the help! :)

**Comment by zaporylie** [comment]
This library facilitates eComm API (in contrast to inApp API). InApp access key is not valid for eComm requests.

**Comment by andreassolemkjaer** [comment]
Oh. I've been using this library to confirm Vipps orders as well as refunding and canceling payments in an inApp payment flow. Is there a change you will be supporting the inApp API like it did in the previous version? Or maybe you could give me some hints in how I could contribute? :)

Or do I simply need to apply for an eComm agreement with Vipps?

**Comment by zaporylie** [comment]
Well, that's interesting :) I never focused on inApp API, simply because there was no use case for me or clients of mine. From brief read of https://www.vipps.no/portalfront/vipps/nedlast/developer/API_documentation_Vipps_eCommerce_and_inApp.pdf seems like all API calls are the same despite which flow in use (common API for operations).

First things first - if you're using production credentials make sure you're using production environment:
https://github.com/zaporylie/php-vipps/wiki/Documentation---1.x#using-production-server

**Comment by andreassolemkjaer** [comment]
Thanks. It seems that the URL for the inApp product is just `/Inapp/v1/...` instead of `/Ecomm/v1/...`, so replacing the URLs in the `Resource/Payment` folder did the trick!

Maybe that switch could be a global configurable variable somewhere...? :)
