### ISSUE TITLE
Support for different URLs for InApp API

### ISSUE THREAD

**Issue by lh-redrock** [zaporylie/php-vipps#20]
In the process of updating to the new token-based authentication, I came across a problem that I cannot see a solution to in the library right now.

The product our customer has is in the developer portal called an "InApp" product. If I attempt to use the Inapp product's credentials on the `https://api.vipps.no/Ecomm/` URLs that this library currently uses, I receive the error:

`{ "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }`

Consulting the documentation on the Vipps developer portal for the Inapp product type (by clicking the "Test the API(s)" link from the product's page), it specifies that the URLs instead take the form `https://api.vipps.no/Inapp/` - by making this change, the credentials for the Inapp product works as expected.

Would it be possible to add a configuration option to have the library use `/Inapp/` instead of `/Ecomm/` - similar to the one that says whether or not to use the live endpoint?

**Comment by zaporylie** [comment]
Unfortunately I don't have access to inapp dev environment so I was never able to test that out. However it seems like supporting `/Inapp` namespace limits to changing path prefix the way you've mentioned. 

In fact Vipps is preparing combined `Ecomm+Inapp` endpoint which will deprecate and replace the way how we connect to their services at the moment, but let's leave that problem aside for the moment...

I think, correct me if I'm wrong, we could provide third, optional parameter to [Vipps::payment()](https://github.com/zaporylie/php-vipps/blob/1.x/src/Vipps.php#L50) and set it up to `Ecomm` for backward compatibility reason, and allow operating in `Inapp` namespace this way. Of course optional param will be propagated to https://github.com/zaporylie/php-vipps/blob/1.x/src/Api/Payment.php#L56 and https://github.com/zaporylie/php-vipps/blob/1.x/src/Resource/ResourceBase.php#L114

Do you think you could test Inapp API if I provide you with a branch/PR with all the changes I've mentioned?

**Comment by zaporylie** [comment]
...and thank you for taking time to create this issue. I much appreciate!

**Comment by lh-redrock** [comment]
Thank you for the fast response. Yes, I would be happy to test it :)

**Comment by zaporylie** [comment]
Ok, check #22 

In `Vipps::Payment` add third parameter - `Inapp`
ex.
```
$payment = $vipps->payment('subscription_key', 'merchant_serial_number', 'Inapp');
```

**Comment by lh-redrock** [comment]
I have tested this with our inapp production credentials, and it works perfectly :)

**Comment by lhadnif** [comment]
Hi! I have come across almost the same issue. I have access to the product "eCommerce InApp Alignment" ecommerce-v2 with the API request URL: https://apitest.vipps.no/ecomm/v2/payments
Have tried using the third parameter as mentioned above but can not get any of my subscription keys to work when i call ->payment(); I thought I should ask If you had any pointers before I start digging more ? thanks

**Comment by zaporylie** [comment]
Hi @lhadnif. Thanks for taking time to write down the comment. As I mentioned in one of the comments above Vipps is working on getting rid of two separate APIs and combining them together into one to rule them all, that is `v2` you just got access to. Unfortunately, version 2 of the API is not supported by this library due to backward incompatible changes to document structure and getting it in would require some more work than just _adding a param_. But feel free to open a new issue and, perhaps, contribute by creating a pull request?
