### ISSUE TITLE
Suggested update to company details

### ISSUE THREAD

**Issue by cloveras** [zaporylie/php-vipps#25]
Hi

Just a suggestion for new Vipps intro:

[Vipps](https://vipps.no) is a Norwegian payment service, used by more than 3 million people. 
Vipps was originally developed by DNB, but is now a separate company, which includes BankID and BankAxept. Vipps developer resources are available on GitHub: https://github.com/vippsas

Christian, Vipps

**Comment by zaporylie** [comment]
Pushed a change to Readme. Thanks.

**Comment by cloveras** [comment]
Thanks! 

I should have remembered to mentioned this too, but: The name is "Vipps" (not "VIPPS"), and the "by DNB" should not be used anymore. The full design guidelines, etc are here: https://github.com/vippsas/vipps-design-guidelines

Also: Nice if the email address is replaced by the words "contact Vipps Integration" and a link to: https://github.com/vippsas/vipps-developers/blob/master/contact.md We get a few emails that do not contain enough information for us to help, so we try to refer to that page as much as possible.

**Comment by zaporylie** [comment]
Fixed. Please open the PR next time you propose a change 👍
