### ISSUE TITLE
Support for Guzzle7

### ISSUE THREAD

**Issue by moody90** [zaporylie/php-vipps#38]
Is there any chance for an update to support Guzzle7-adapter?
Tried adding this to a new Laravel 9 project and got compatibility issues since Laravel already includes Guzzle7.

**Comment by zaporylie** [comment]
Hi, sorry for the late reply. I guess the problem here is not guzzle7-adapter per se, as guzzle is not a direct dependency here, but support for `php-http/httplug ^2.0` which is required by guzzle7-adapter?

**Comment by zaporylie** [comment]
From what I can tell, from this library perspective we can simply open up for both `php-http/httplug: ^1.0 || ^2.0` as per https://github.com/php-http/httplug/blob/master/CHANGELOG.md#200---2018-10-31

> This version is no BC break for consumers using HTTPlug
